/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 15
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CR_LF = 1,
  anon_sym_LF = 2,
  anon_sym_SPACE = 3,
  sym_digit = 4,
  anon_sym_HTTP_SLASH = 5,
  anon_sym_DOT = 6,
  sym_method = 7,
  sym_request_target = 8,
  sym_source_file = 9,
  sym__line_ending = 10,
  sym__SP = 11,
  sym_http_version = 12,
  sym_request_line = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_LF] = "\n",
  [anon_sym_SPACE] = " ",
  [sym_digit] = "digit",
  [anon_sym_HTTP_SLASH] = "HTTP/",
  [anon_sym_DOT] = ".",
  [sym_method] = "method",
  [sym_request_target] = "request_target",
  [sym_source_file] = "source_file",
  [sym__line_ending] = "_line_ending",
  [sym__SP] = "_SP",
  [sym_http_version] = "http_version",
  [sym_request_line] = "request_line",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_digit] = sym_digit,
  [anon_sym_HTTP_SLASH] = anon_sym_HTTP_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_method] = sym_method,
  [sym_request_target] = sym_request_target,
  [sym_source_file] = sym_source_file,
  [sym__line_ending] = sym__line_ending,
  [sym__SP] = sym__SP,
  [sym_http_version] = sym_http_version,
  [sym_request_line] = sym_request_line,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_digit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_HTTP_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_request_target] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__SP] = {
    .visible = false,
    .named = true,
  },
  [sym_http_version] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_major = 1,
  field_method = 2,
  field_minor = 3,
  field_target = 4,
  field_version = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_major] = "major",
  [field_method] = "method",
  [field_minor] = "minor",
  [field_target] = "target",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_method, 0},
    {field_target, 2},
  [2] =
    {field_method, 0},
    {field_target, 2},
    {field_version, 4},
  [5] =
    {field_major, 1},
    {field_minor, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
};

static const TSCharacterRange sym_method_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '.'}, {'0', '9'}, {'A', 'Z'}, {'^', 'z'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(11);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == 'H') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'P') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == 'T') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 'T') ADVANCE(4);
      END_STATE();
    case 6:
      if (set_contains(sym_method_character_set_1, 9, lookahead)) ADVANCE(15);
      END_STATE();
    case 7:
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(16);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_digit);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_HTTP_SLASH);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_method);
      if (set_contains(sym_method_character_set_1, 9, lookahead)) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_request_target);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [sym_digit] = ACTIONS(1),
    [anon_sym_HTTP_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym_request_line] = STATE(8),
    [sym_method] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      anon_sym_SPACE,
    STATE(5), 1,
      sym__SP,
    STATE(10), 1,
      sym__line_ending,
    ACTIONS(5), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [14] = 2,
    STATE(13), 1,
      sym__line_ending,
    ACTIONS(9), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [22] = 2,
    ACTIONS(11), 1,
      anon_sym_SPACE,
    STATE(9), 1,
      sym__SP,
  [29] = 2,
    ACTIONS(13), 1,
      anon_sym_HTTP_SLASH,
    STATE(3), 1,
      sym_http_version,
  [36] = 1,
    ACTIONS(15), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [41] = 1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
  [45] = 1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
  [49] = 1,
    ACTIONS(21), 1,
      sym_request_target,
  [53] = 1,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [57] = 1,
    ACTIONS(25), 1,
      sym_digit,
  [61] = 1,
    ACTIONS(27), 1,
      anon_sym_DOT,
  [65] = 1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
  [69] = 1,
    ACTIONS(31), 1,
      sym_digit,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 22,
  [SMALL_STATE(5)] = 29,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 41,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 49,
  [SMALL_STATE(10)] = 53,
  [SMALL_STATE(11)] = 57,
  [SMALL_STATE(12)] = 61,
  [SMALL_STATE(13)] = 65,
  [SMALL_STATE(14)] = 69,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_http_version, 4, 0, 3),
  [17] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 4, 0, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 6, 0, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_http(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "http",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
