/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 72
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_CR_LF = 1,
  anon_sym_LF = 2,
  sym__wsp = 3,
  sym_digit = 4,
  anon_sym_POUND_POUND_POUND = 5,
  sym_request_name = 6,
  aux_sym_method_token1 = 7,
  sym_request_target = 8,
  sym_field_value = 9,
  sym_field_value_seperator = 10,
  anon_sym_ATfield = 11,
  anon_sym_ATfile = 12,
  aux_sym_multipart_part_token1 = 13,
  anon_sym_HTTP_SLASH = 14,
  anon_sym_DOT = 15,
  sym__octet_body = 16,
  sym_source_file = 17,
  sym__line_ending = 18,
  sym_octet_body = 19,
  sym_seprator = 20,
  sym_method = 21,
  sym_field_name = 22,
  sym_multipart_part = 23,
  sym_multipart_body = 24,
  sym_message_body = 25,
  sym_http_version = 26,
  sym_request_line = 27,
  sym_field_line = 28,
  sym_request_block = 29,
  aux_sym_source_file_repeat1 = 30,
  aux_sym_source_file_repeat2 = 31,
  aux_sym_seprator_repeat1 = 32,
  aux_sym_multipart_body_repeat1 = 33,
  aux_sym_request_block_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_LF] = "\n",
  [sym__wsp] = "_wsp",
  [sym_digit] = "digit",
  [anon_sym_POUND_POUND_POUND] = "###",
  [sym_request_name] = "request_name",
  [aux_sym_method_token1] = "method_token1",
  [sym_request_target] = "request_target",
  [sym_field_value] = "field_value",
  [sym_field_value_seperator] = "field_value_seperator",
  [anon_sym_ATfield] = "@field",
  [anon_sym_ATfile] = "@file",
  [aux_sym_multipart_part_token1] = "multipart_part_token1",
  [anon_sym_HTTP_SLASH] = "HTTP/",
  [anon_sym_DOT] = ".",
  [sym__octet_body] = "_octet_body",
  [sym_source_file] = "source_file",
  [sym__line_ending] = "_line_ending",
  [sym_octet_body] = "octet_body",
  [sym_seprator] = "seprator",
  [sym_method] = "method",
  [sym_field_name] = "field_name",
  [sym_multipart_part] = "multipart_part",
  [sym_multipart_body] = "multipart_body",
  [sym_message_body] = "message_body",
  [sym_http_version] = "http_version",
  [sym_request_line] = "request_line",
  [sym_field_line] = "field_line",
  [sym_request_block] = "request_block",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_seprator_repeat1] = "seprator_repeat1",
  [aux_sym_multipart_body_repeat1] = "multipart_body_repeat1",
  [aux_sym_request_block_repeat1] = "request_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_LF] = anon_sym_LF,
  [sym__wsp] = sym__wsp,
  [sym_digit] = sym_digit,
  [anon_sym_POUND_POUND_POUND] = anon_sym_POUND_POUND_POUND,
  [sym_request_name] = sym_request_name,
  [aux_sym_method_token1] = aux_sym_method_token1,
  [sym_request_target] = sym_request_target,
  [sym_field_value] = sym_field_value,
  [sym_field_value_seperator] = sym_field_value_seperator,
  [anon_sym_ATfield] = anon_sym_ATfield,
  [anon_sym_ATfile] = anon_sym_ATfile,
  [aux_sym_multipart_part_token1] = aux_sym_multipart_part_token1,
  [anon_sym_HTTP_SLASH] = anon_sym_HTTP_SLASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym__octet_body] = sym__octet_body,
  [sym_source_file] = sym_source_file,
  [sym__line_ending] = sym__line_ending,
  [sym_octet_body] = sym_octet_body,
  [sym_seprator] = sym_seprator,
  [sym_method] = sym_method,
  [sym_field_name] = sym_field_name,
  [sym_multipart_part] = sym_multipart_part,
  [sym_multipart_body] = sym_multipart_body,
  [sym_message_body] = sym_message_body,
  [sym_http_version] = sym_http_version,
  [sym_request_line] = sym_request_line,
  [sym_field_line] = sym_field_line,
  [sym_request_block] = sym_request_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_seprator_repeat1] = aux_sym_seprator_repeat1,
  [aux_sym_multipart_body_repeat1] = aux_sym_multipart_body_repeat1,
  [aux_sym_request_block_repeat1] = aux_sym_request_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym__wsp] = {
    .visible = false,
    .named = true,
  },
  [sym_digit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_request_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_method_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_request_target] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value] = {
    .visible = true,
    .named = true,
  },
  [sym_field_value_seperator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATfield] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ATfile] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multipart_part_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_HTTP_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym__octet_body] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym_octet_body] = {
    .visible = true,
    .named = true,
  },
  [sym_seprator] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_field_name] = {
    .visible = true,
    .named = true,
  },
  [sym_multipart_part] = {
    .visible = true,
    .named = true,
  },
  [sym_multipart_body] = {
    .visible = true,
    .named = true,
  },
  [sym_message_body] = {
    .visible = true,
    .named = true,
  },
  [sym_http_version] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_field_line] = {
    .visible = true,
    .named = true,
  },
  [sym_request_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_seprator_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multipart_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_major = 1,
  field_method = 2,
  field_minor = 3,
  field_name = 4,
  field_target = 5,
  field_value = 6,
  field_version = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_major] = "major",
  [field_method] = "method",
  [field_minor] = "minor",
  [field_name] = "name",
  [field_target] = "target",
  [field_value] = "value",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
  [5] = {.index = 8, .length = 2},
  [6] = {.index = 10, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 2},
  [1] =
    {field_method, 0},
    {field_target, 2},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_method, 0},
    {field_target, 2},
    {field_version, 4},
  [8] =
    {field_name, 0},
    {field_value, 3},
  [10] =
    {field_major, 1},
    {field_minor, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 22,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 34,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
};

static const TSCharacterRange aux_sym_method_token1_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '.'}, {'0', '9'}, {'A', 'Z'}, {'^', 'z'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 4,
        '#', 6,
        '.', 39,
        ':', 34,
        '@', 14,
        'H', 10,
        '\t', 23,
        ' ', 23,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(23);
      if (lookahead == ' ') ADVANCE(24);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(28);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(33);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(4);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == 'P') ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == 'T') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(35);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(16);
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(15);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(33);
      END_STATE();
    case 18:
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(32);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead == '#') ADVANCE(30);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__wsp);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__wsp);
      if ((' ' <= lookahead && lookahead <= '~')) ADVANCE(28);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_digit);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_request_name);
      if ((' ' <= lookahead && lookahead <= '~')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_method_token1);
      if (lookahead == '#') ADVANCE(27);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_method_token1);
      if (lookahead == '#') ADVANCE(29);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_method_token1);
      if (set_contains(aux_sym_method_token1_character_set_1, 9, lookahead)) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_request_target);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_field_value);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_field_value_seperator);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_ATfield);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_ATfile);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_multipart_part_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_HTTP_SLASH);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 19},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 19},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 19},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 18},
  [66] = {.lex_state = 37},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym__wsp] = ACTIONS(1),
    [sym_digit] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(1),
    [sym_field_value_seperator] = ACTIONS(1),
    [anon_sym_ATfield] = ACTIONS(1),
    [anon_sym_ATfile] = ACTIONS(1),
    [anon_sym_HTTP_SLASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__octet_body] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(71),
    [sym__line_ending] = STATE(4),
    [sym_seprator] = STATE(44),
    [sym_method] = STATE(62),
    [sym_request_line] = STATE(20),
    [sym_request_block] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(4),
    [anon_sym_CR_LF] = ACTIONS(3),
    [anon_sym_LF] = ACTIONS(3),
    [anon_sym_POUND_POUND_POUND] = ACTIONS(5),
    [aux_sym_method_token1] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      sym__octet_body,
    STATE(43), 1,
      sym_message_body,
    ACTIONS(11), 2,
      anon_sym_ATfield,
      anon_sym_ATfile,
    STATE(9), 2,
      sym_multipart_part,
      aux_sym_multipart_body_repeat1,
    STATE(42), 2,
      sym_octet_body,
      sym_multipart_body,
    ACTIONS(9), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [25] = 6,
    ACTIONS(13), 1,
      sym__octet_body,
    STATE(38), 1,
      sym_message_body,
    ACTIONS(11), 2,
      anon_sym_ATfield,
      anon_sym_ATfile,
    STATE(9), 2,
      sym_multipart_part,
      aux_sym_multipart_body_repeat1,
    STATE(42), 2,
      sym_octet_body,
      sym_multipart_body,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [50] = 8,
    ACTIONS(5), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(7), 1,
      aux_sym_method_token1,
    STATE(7), 1,
      sym_request_block,
    STATE(20), 1,
      sym_request_line,
    STATE(37), 1,
      sym_seprator,
    STATE(62), 1,
      sym_method,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [77] = 6,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(20), 1,
      sym_request_line,
    STATE(35), 1,
      sym_request_block,
    STATE(62), 1,
      sym_method,
    ACTIONS(19), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(10), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [98] = 6,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(5), 1,
      sym_seprator,
    STATE(8), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(25), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(21), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [119] = 6,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_seprator,
    STATE(16), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(31), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(23), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [140] = 6,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_seprator,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(31), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(23), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [161] = 3,
    ACTIONS(11), 2,
      anon_sym_ATfield,
      anon_sym_ATfile,
    STATE(15), 2,
      sym_multipart_part,
      aux_sym_multipart_body_repeat1,
    ACTIONS(33), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [176] = 6,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(20), 1,
      sym_request_line,
    STATE(39), 1,
      sym_request_block,
    STATE(62), 1,
      sym_method,
    ACTIONS(35), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(33), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [197] = 6,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(20), 1,
      sym_request_line,
    STATE(39), 1,
      sym_request_block,
    STATE(62), 1,
      sym_method,
    ACTIONS(37), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(14), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [218] = 6,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(44), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(5), 1,
      sym_seprator,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(41), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(27), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [239] = 6,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_seprator,
    STATE(17), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(49), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(24), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [260] = 6,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(20), 1,
      sym_request_line,
    STATE(36), 1,
      sym_request_block,
    STATE(62), 1,
      sym_method,
    ACTIONS(35), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(33), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [281] = 3,
    ACTIONS(53), 2,
      anon_sym_ATfield,
      anon_sym_ATfile,
    STATE(15), 2,
      sym_multipart_part,
      aux_sym_multipart_body_repeat1,
    ACTIONS(51), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [296] = 6,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_seprator,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(49), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(24), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [317] = 6,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_seprator,
    STATE(12), 1,
      aux_sym_source_file_repeat2,
    ACTIONS(58), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(18), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [338] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_seprator,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [356] = 5,
    ACTIONS(64), 1,
      aux_sym_method_token1,
    STATE(3), 1,
      sym__line_ending,
    STATE(70), 1,
      sym_field_name,
    ACTIONS(62), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(26), 2,
      sym_field_line,
      aux_sym_request_block_repeat1,
  [374] = 5,
    ACTIONS(64), 1,
      aux_sym_method_token1,
    STATE(2), 1,
      sym__line_ending,
    STATE(70), 1,
      sym_field_name,
    ACTIONS(66), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(19), 2,
      sym_field_line,
      aux_sym_request_block_repeat1,
  [392] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_seprator,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [410] = 4,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    ACTIONS(73), 2,
      anon_sym_POUND_POUND_POUND,
      aux_sym_method_token1,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [426] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_seprator,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [444] = 5,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_seprator,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [462] = 1,
    ACTIONS(75), 6,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
      anon_sym_ATfield,
      anon_sym_ATfile,
  [471] = 4,
    ACTIONS(79), 1,
      aux_sym_method_token1,
    STATE(70), 1,
      sym_field_name,
    ACTIONS(77), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(26), 2,
      sym_field_line,
      aux_sym_request_block_repeat1,
  [486] = 4,
    ACTIONS(27), 1,
      anon_sym_POUND_POUND_POUND,
    STATE(11), 1,
      sym_seprator,
    ACTIONS(17), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [501] = 4,
    ACTIONS(84), 1,
      sym__wsp,
    STATE(45), 1,
      sym__line_ending,
    STATE(49), 1,
      aux_sym_seprator_repeat1,
    ACTIONS(82), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [515] = 4,
    ACTIONS(88), 1,
      sym__wsp,
    STATE(34), 1,
      aux_sym_seprator_repeat1,
    STATE(57), 1,
      sym__line_ending,
    ACTIONS(86), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [529] = 4,
    ACTIONS(92), 1,
      sym__wsp,
    STATE(29), 1,
      aux_sym_seprator_repeat1,
    STATE(50), 1,
      sym__line_ending,
    ACTIONS(90), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [543] = 4,
    ACTIONS(96), 1,
      sym__wsp,
    STATE(32), 1,
      aux_sym_seprator_repeat1,
    STATE(56), 1,
      sym__line_ending,
    ACTIONS(94), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [557] = 4,
    ACTIONS(88), 1,
      sym__wsp,
    STATE(34), 1,
      aux_sym_seprator_repeat1,
    STATE(58), 1,
      sym__line_ending,
    ACTIONS(98), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [571] = 3,
    ACTIONS(68), 1,
      aux_sym_method_token1,
    ACTIONS(100), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
    STATE(33), 2,
      sym__line_ending,
      aux_sym_source_file_repeat1,
  [583] = 3,
    ACTIONS(105), 1,
      sym__wsp,
    STATE(34), 1,
      aux_sym_seprator_repeat1,
    ACTIONS(103), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      sym_field_value,
  [595] = 1,
    ACTIONS(39), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [602] = 1,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [609] = 4,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(13), 1,
      sym_request_block,
    STATE(20), 1,
      sym_request_line,
    STATE(62), 1,
      sym_method,
  [622] = 1,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [629] = 1,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [636] = 3,
    ACTIONS(116), 1,
      sym__wsp,
    STATE(54), 1,
      sym__line_ending,
    ACTIONS(114), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [647] = 1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [654] = 1,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [661] = 1,
    ACTIONS(15), 4,
      ts_builtin_sym_end,
      anon_sym_CR_LF,
      anon_sym_LF,
      anon_sym_POUND_POUND_POUND,
  [668] = 4,
    ACTIONS(21), 1,
      aux_sym_method_token1,
    STATE(7), 1,
      sym_request_block,
    STATE(20), 1,
      sym_request_line,
    STATE(62), 1,
      sym_method,
  [681] = 1,
    ACTIONS(122), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [687] = 3,
    ACTIONS(124), 1,
      sym__wsp,
    ACTIONS(127), 1,
      sym_request_name,
    STATE(46), 1,
      aux_sym_seprator_repeat1,
  [697] = 3,
    ACTIONS(88), 1,
      sym__wsp,
    ACTIONS(129), 1,
      sym_field_value,
    STATE(34), 1,
      aux_sym_seprator_repeat1,
  [707] = 2,
    STATE(52), 1,
      sym__line_ending,
    ACTIONS(131), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [715] = 3,
    ACTIONS(133), 1,
      sym__wsp,
    ACTIONS(135), 1,
      sym_request_name,
    STATE(46), 1,
      aux_sym_seprator_repeat1,
  [725] = 1,
    ACTIONS(137), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [731] = 2,
    STATE(53), 1,
      sym__line_ending,
    ACTIONS(139), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [739] = 1,
    ACTIONS(141), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [745] = 1,
    ACTIONS(143), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [751] = 1,
    ACTIONS(145), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [757] = 2,
    STATE(25), 1,
      sym__line_ending,
    ACTIONS(147), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [765] = 1,
    ACTIONS(149), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [771] = 1,
    ACTIONS(151), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [777] = 1,
    ACTIONS(153), 3,
      anon_sym_CR_LF,
      anon_sym_LF,
      aux_sym_method_token1,
  [783] = 3,
    ACTIONS(155), 1,
      sym__wsp,
    ACTIONS(157), 1,
      sym_field_value,
    STATE(47), 1,
      aux_sym_seprator_repeat1,
  [793] = 2,
    ACTIONS(159), 1,
      anon_sym_HTTP_SLASH,
    STATE(51), 1,
      sym_http_version,
  [800] = 1,
    ACTIONS(161), 2,
      anon_sym_CR_LF,
      anon_sym_LF,
  [805] = 1,
    ACTIONS(163), 1,
      sym__wsp,
  [809] = 1,
    ACTIONS(165), 1,
      sym_digit,
  [813] = 1,
    ACTIONS(167), 1,
      sym_field_value_seperator,
  [817] = 1,
    ACTIONS(169), 1,
      sym_request_target,
  [821] = 1,
    ACTIONS(171), 1,
      aux_sym_multipart_part_token1,
  [825] = 1,
    ACTIONS(173), 1,
      sym__wsp,
  [829] = 1,
    ACTIONS(175), 1,
      sym_digit,
  [833] = 1,
    ACTIONS(177), 1,
      anon_sym_DOT,
  [837] = 1,
    ACTIONS(179), 1,
      sym_field_value_seperator,
  [841] = 1,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 25,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 77,
  [SMALL_STATE(6)] = 98,
  [SMALL_STATE(7)] = 119,
  [SMALL_STATE(8)] = 140,
  [SMALL_STATE(9)] = 161,
  [SMALL_STATE(10)] = 176,
  [SMALL_STATE(11)] = 197,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 239,
  [SMALL_STATE(14)] = 260,
  [SMALL_STATE(15)] = 281,
  [SMALL_STATE(16)] = 296,
  [SMALL_STATE(17)] = 317,
  [SMALL_STATE(18)] = 338,
  [SMALL_STATE(19)] = 356,
  [SMALL_STATE(20)] = 374,
  [SMALL_STATE(21)] = 392,
  [SMALL_STATE(22)] = 410,
  [SMALL_STATE(23)] = 426,
  [SMALL_STATE(24)] = 444,
  [SMALL_STATE(25)] = 462,
  [SMALL_STATE(26)] = 471,
  [SMALL_STATE(27)] = 486,
  [SMALL_STATE(28)] = 501,
  [SMALL_STATE(29)] = 515,
  [SMALL_STATE(30)] = 529,
  [SMALL_STATE(31)] = 543,
  [SMALL_STATE(32)] = 557,
  [SMALL_STATE(33)] = 571,
  [SMALL_STATE(34)] = 583,
  [SMALL_STATE(35)] = 595,
  [SMALL_STATE(36)] = 602,
  [SMALL_STATE(37)] = 609,
  [SMALL_STATE(38)] = 622,
  [SMALL_STATE(39)] = 629,
  [SMALL_STATE(40)] = 636,
  [SMALL_STATE(41)] = 647,
  [SMALL_STATE(42)] = 654,
  [SMALL_STATE(43)] = 661,
  [SMALL_STATE(44)] = 668,
  [SMALL_STATE(45)] = 681,
  [SMALL_STATE(46)] = 687,
  [SMALL_STATE(47)] = 697,
  [SMALL_STATE(48)] = 707,
  [SMALL_STATE(49)] = 715,
  [SMALL_STATE(50)] = 725,
  [SMALL_STATE(51)] = 731,
  [SMALL_STATE(52)] = 739,
  [SMALL_STATE(53)] = 745,
  [SMALL_STATE(54)] = 751,
  [SMALL_STATE(55)] = 757,
  [SMALL_STATE(56)] = 765,
  [SMALL_STATE(57)] = 771,
  [SMALL_STATE(58)] = 777,
  [SMALL_STATE(59)] = 783,
  [SMALL_STATE(60)] = 793,
  [SMALL_STATE(61)] = 800,
  [SMALL_STATE(62)] = 805,
  [SMALL_STATE(63)] = 809,
  [SMALL_STATE(64)] = 813,
  [SMALL_STATE(65)] = 817,
  [SMALL_STATE(66)] = 821,
  [SMALL_STATE(67)] = 825,
  [SMALL_STATE(68)] = 829,
  [SMALL_STATE(69)] = 833,
  [SMALL_STATE(70)] = 837,
  [SMALL_STATE(71)] = 841,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 2, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 3, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipart_body, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(27),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multipart_body_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multipart_body_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multipart_part, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_request_block_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_request_block_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_seprator_repeat1, 2, 0, 0),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_seprator_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_block, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_octet_body, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_body, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seprator, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_seprator_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_seprator_repeat1, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 4, 0, 3),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_seprator, 4, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 6, 0, 4),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 4, 0, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 5, 0, 5),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 5, 0, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_line, 6, 0, 5),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_http_version, 4, 0, 6),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_name, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [181] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__octet_body = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__octet_body] = sym__octet_body,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__octet_body] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_probe_external_scanner_create(void);
void tree_sitter_probe_external_scanner_destroy(void *);
bool tree_sitter_probe_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_probe_external_scanner_serialize(void *, char *);
void tree_sitter_probe_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_probe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_probe_external_scanner_create,
      tree_sitter_probe_external_scanner_destroy,
      tree_sitter_probe_external_scanner_scan,
      tree_sitter_probe_external_scanner_serialize,
      tree_sitter_probe_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "probe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
