/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_GET = 1,
  anon_sym_POST = 2,
  anon_sym_PUT = 3,
  anon_sym_DELETE = 4,
  anon_sym_PATCH = 5,
  anon_sym_HEAD = 6,
  anon_sym_OPTIONS = 7,
  anon_sym_CONNECT = 8,
  anon_sym_TRACE = 9,
  aux_sym_request_target_token1 = 10,
  aux_sym_request_target_token2 = 11,
  sym_http_version = 12,
  sym_source_file = 13,
  sym_request_type = 14,
  sym_request_target = 15,
  sym_request_line = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_GET] = "GET",
  [anon_sym_POST] = "POST",
  [anon_sym_PUT] = "PUT",
  [anon_sym_DELETE] = "DELETE",
  [anon_sym_PATCH] = "PATCH",
  [anon_sym_HEAD] = "HEAD",
  [anon_sym_OPTIONS] = "OPTIONS",
  [anon_sym_CONNECT] = "CONNECT",
  [anon_sym_TRACE] = "TRACE",
  [aux_sym_request_target_token1] = "request_target_token1",
  [aux_sym_request_target_token2] = "request_target_token2",
  [sym_http_version] = "http_version",
  [sym_source_file] = "source_file",
  [sym_request_type] = "request_type",
  [sym_request_target] = "request_target",
  [sym_request_line] = "request_line",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_GET] = anon_sym_GET,
  [anon_sym_POST] = anon_sym_POST,
  [anon_sym_PUT] = anon_sym_PUT,
  [anon_sym_DELETE] = anon_sym_DELETE,
  [anon_sym_PATCH] = anon_sym_PATCH,
  [anon_sym_HEAD] = anon_sym_HEAD,
  [anon_sym_OPTIONS] = anon_sym_OPTIONS,
  [anon_sym_CONNECT] = anon_sym_CONNECT,
  [anon_sym_TRACE] = anon_sym_TRACE,
  [aux_sym_request_target_token1] = aux_sym_request_target_token1,
  [aux_sym_request_target_token2] = aux_sym_request_target_token2,
  [sym_http_version] = sym_http_version,
  [sym_source_file] = sym_source_file,
  [sym_request_type] = sym_request_type,
  [sym_request_target] = sym_request_target,
  [sym_request_line] = sym_request_line,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_GET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DELETE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PATCH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_HEAD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OPTIONS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CONNECT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_request_target_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_target_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_http_version] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_request_type] = {
    .visible = true,
    .named = true,
  },
  [sym_request_target] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_target = 1,
  field_type = 2,
  field_version = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_target] = "target",
  [field_type] = "type",
  [field_version] = "version",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_target, 1},
    {field_type, 0},
  [2] =
    {field_target, 1},
    {field_type, 0},
    {field_version, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      ADVANCE_MAP(
        '/', 58,
        'C', 26,
        'D', 13,
        'G', 14,
        'H', 15,
        'O', 29,
        'P', 8,
        'T', 30,
        'h', 43,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(44);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(46);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == 's') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(35);
      if (lookahead == 'O') ADVANCE(32);
      if (lookahead == 'U') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == 'C') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'C') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'C') ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'D') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(6);
      if (lookahead == 'T') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(51);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 20:
      if (lookahead == 'H') ADVANCE(52);
      END_STATE();
    case 21:
      if (lookahead == 'I') ADVANCE(27);
      END_STATE();
    case 22:
      if (lookahead == 'L') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'N') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 'N') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'N') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 'O') ADVANCE(23);
      END_STATE();
    case 27:
      if (lookahead == 'O') ADVANCE(24);
      END_STATE();
    case 28:
      if (lookahead == 'P') ADVANCE(1);
      END_STATE();
    case 29:
      if (lookahead == 'P') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(7);
      END_STATE();
    case 31:
      if (lookahead == 'S') ADVANCE(54);
      END_STATE();
    case 32:
      if (lookahead == 'S') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(21);
      END_STATE();
    case 35:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 36:
      if (lookahead == 'T') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 'T') ADVANCE(49);
      END_STATE();
    case 38:
      if (lookahead == 'T') ADVANCE(55);
      END_STATE();
    case 39:
      if (lookahead == 'T') ADVANCE(28);
      END_STATE();
    case 40:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 41:
      if (lookahead == 'p') ADVANCE(5);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GET);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_POST);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PUT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DELETE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PATCH);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_HEAD);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_OPTIONS);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_CONNECT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_TRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_request_target_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_request_target_token2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_http_version);
      if (lookahead == '.') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_http_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_GET] = ACTIONS(1),
    [anon_sym_POST] = ACTIONS(1),
    [anon_sym_PUT] = ACTIONS(1),
    [anon_sym_DELETE] = ACTIONS(1),
    [anon_sym_PATCH] = ACTIONS(1),
    [anon_sym_HEAD] = ACTIONS(1),
    [anon_sym_OPTIONS] = ACTIONS(1),
    [anon_sym_CONNECT] = ACTIONS(1),
    [anon_sym_TRACE] = ACTIONS(1),
    [aux_sym_request_target_token1] = ACTIONS(1),
    [aux_sym_request_target_token2] = ACTIONS(1),
    [sym_http_version] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(6),
    [sym_request_type] = STATE(2),
    [sym_request_line] = STATE(7),
    [anon_sym_GET] = ACTIONS(3),
    [anon_sym_POST] = ACTIONS(3),
    [anon_sym_PUT] = ACTIONS(3),
    [anon_sym_DELETE] = ACTIONS(3),
    [anon_sym_PATCH] = ACTIONS(3),
    [anon_sym_HEAD] = ACTIONS(3),
    [anon_sym_OPTIONS] = ACTIONS(3),
    [anon_sym_CONNECT] = ACTIONS(3),
    [anon_sym_TRACE] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(5), 1,
      sym_request_target,
    ACTIONS(5), 2,
      aux_sym_request_target_token1,
      aux_sym_request_target_token2,
  [8] = 1,
    ACTIONS(7), 2,
      aux_sym_request_target_token1,
      aux_sym_request_target_token2,
  [13] = 1,
    ACTIONS(9), 2,
      ts_builtin_sym_end,
      sym_http_version,
  [18] = 2,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_http_version,
  [25] = 1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
  [29] = 1,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
  [33] = 1,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 8,
  [SMALL_STATE(4)] = 13,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 25,
  [SMALL_STATE(7)] = 29,
  [SMALL_STATE(8)] = 33,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_type, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_target, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 3, 0, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_probe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "probe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
