// Code generated by gen/main.go from node-types.json. DO NOT EDIT.

package ast

import ts "github.com/tree-sitter/go-tree-sitter"

type NodeKind string

const (
	AccessorKind            NodeKind = "accessor"
	ArgumentKind            NodeKind = "argument"
	ArgumentsKind           NodeKind = "arguments"
	AssertDirectiveKind     NodeKind = "assert_directive"
	AssertTargetKind        NodeKind = "assert_target"
	BodyTargetKind          NodeKind = "body_target"
	ComparatorOperatorKind  NodeKind = "comparator_operator"
	DigitKind               NodeKind = "digit"
	DirectiveLineKind       NodeKind = "directive_line"
	FieldLineKind           NodeKind = "field_line"
	FieldNameKind           NodeKind = "field_name"
	FieldValueKind          NodeKind = "field_value"
	FieldValueSeperatorKind NodeKind = "field_value_seperator"
	HeaderTargetKind        NodeKind = "header_target"
	HttpVersionKind         NodeKind = "http_version"
	IdentifierKind          NodeKind = "identifier"
	IndexAccessKind         NodeKind = "index_access"
	InterpolationKind       NodeKind = "interpolation"
	InterpolationBodyKind   NodeKind = "interpolation_body"
	JsonLiteralKind         NodeKind = "json_literal"
	LetDirectiveKind        NodeKind = "let_directive"
	LetValueKind            NodeKind = "let_value"
	MemberAccessKind        NodeKind = "member_access"
	MessageBodyKind         NodeKind = "message_body"
	MethodKind              NodeKind = "method"
	MultipartBodyKind       NodeKind = "multipart_body"
	MultipartPartKind       NodeKind = "multipart_part"
	NumberKind              NodeKind = "number"
	OctetBodyKind           NodeKind = "octet_body"
	RequestBlockKind        NodeKind = "request_block"
	RequestLineKind         NodeKind = "request_line"
	RequestNameKind         NodeKind = "request_name"
	RequestTargetKind       NodeKind = "request_target"
	SaveDirectiveKind       NodeKind = "save_directive"
	SepratorKind            NodeKind = "seprator"
	SourceFileKind          NodeKind = "source_file"
	StringKind              NodeKind = "string"
	UtilReferenceKind       NodeKind = "util_reference"
	ValueReferenceKind      NodeKind = "value_reference"
)

// AccessorNode represents a accessor node.
type AccessorNode struct {
	TSNode *ts.Node
}

// ArgumentNode represents a argument node.
type ArgumentNode struct {
	TSNode *ts.Node
	Value  *ts.Node // field: value
}

// ArgumentsNode represents a arguments node.
type ArgumentsNode struct {
	TSNode   *ts.Node
	Argument []*ArgumentNode // field: argument
}

// AssertDirectiveNode represents a assert_directive node.
type AssertDirectiveNode struct {
	TSNode     *ts.Node
	Comparator *ComparatorOperatorNode // field: comparator
	Expected   *LetValueNode           // field: expected
	Target     *AssertTargetNode       // field: target
}

// AssertTargetNode represents a assert_target node.
type AssertTargetNode struct {
	TSNode *ts.Node
	Target *ts.Node // field: target
}

// BodyTargetNode represents a body_target node.
type BodyTargetNode struct {
	TSNode   *ts.Node
	Accessor []*AccessorNode // field: accessor
}

// ComparatorOperatorNode represents a comparator_operator node.
type ComparatorOperatorNode struct {
	TSNode *ts.Node
}

// DigitNode represents a digit node.
type DigitNode struct {
	TSNode *ts.Node
}

// DirectiveLineNode represents a directive_line node.
type DirectiveLineNode struct {
	TSNode    *ts.Node
	Directive *ts.Node // field: directive
}

// FieldLineNode represents a field_line node.
type FieldLineNode struct {
	TSNode *ts.Node
	Name   *FieldNameNode  // field: name
	Value  *FieldValueNode // field: value
}

// FieldNameNode represents a field_name node.
type FieldNameNode struct {
	TSNode *ts.Node
}

// FieldValueNode represents a field_value node.
type FieldValueNode struct {
	TSNode        *ts.Node
	Interpolation []*InterpolationNode // field: interpolation
}

// FieldValueSeperatorNode represents a field_value_seperator node.
type FieldValueSeperatorNode struct {
	TSNode *ts.Node
}

// HeaderTargetNode represents a header_target node.
type HeaderTargetNode struct {
	TSNode *ts.Node
	Name   *FieldNameNode // field: name
}

// HttpVersionNode represents a http_version node.
type HttpVersionNode struct {
	TSNode *ts.Node
	Major  *DigitNode // field: major
	Minor  *DigitNode // field: minor
}

// IdentifierNode represents a identifier node.
type IdentifierNode struct {
	TSNode *ts.Node
}

// IndexAccessNode represents a index_access node.
type IndexAccessNode struct {
	TSNode *ts.Node
	Index  *ts.Node // field: index
}

// InterpolationNode represents a interpolation node.
type InterpolationNode struct {
	TSNode *ts.Node
	Body   *InterpolationBodyNode // field: body
}

// InterpolationBodyNode represents a interpolation_body node.
type InterpolationBodyNode struct {
	TSNode *ts.Node
	Ref    *ts.Node // field: ref
}

// JsonLiteralNode represents a json_literal node.
type JsonLiteralNode struct {
	TSNode *ts.Node
	Value  *ts.Node // field: value
}

// LetDirectiveNode represents a let_directive node.
type LetDirectiveNode struct {
	TSNode *ts.Node
	Name   *IdentifierNode // field: name
	Target *LetValueNode   // field: target
}

// LetValueNode represents a let_value node.
type LetValueNode struct {
	TSNode *ts.Node
	Value  *ts.Node // field: value
}

// MemberAccessNode represents a member_access node.
type MemberAccessNode struct {
	TSNode *ts.Node
	Name   *IdentifierNode // field: name
}

// MessageBodyNode represents a message_body node.
type MessageBodyNode struct {
	TSNode *ts.Node
	Body   *ts.Node // field: body
}

// MethodNode represents a method node.
type MethodNode struct {
	TSNode *ts.Node
}

// MultipartBodyNode represents a multipart_body node.
type MultipartBodyNode struct {
	TSNode *ts.Node
	Part   []*MultipartPartNode // field: part
}

// MultipartPartNode represents a multipart_part node.
type MultipartPartNode struct {
	TSNode *ts.Node
}

// NumberNode represents a number node.
type NumberNode struct {
	TSNode *ts.Node
}

// OctetBodyNode represents a octet_body node.
type OctetBodyNode struct {
	TSNode *ts.Node
}

// RequestBlockNode represents a request_block node.
type RequestBlockNode struct {
	TSNode      *ts.Node
	Body        *MessageBodyNode     // field: body
	Directive   []*DirectiveLineNode // field: directive
	FieldLine   []*FieldLineNode     // field: field_line
	RequestLine *RequestLineNode     // field: request_line
}

// RequestLineNode represents a request_line node.
type RequestLineNode struct {
	TSNode  *ts.Node
	Method  *MethodNode        // field: method
	Target  *RequestTargetNode // field: target
	Version *HttpVersionNode   // field: version
}

// RequestNameNode represents a request_name node.
type RequestNameNode struct {
	TSNode *ts.Node
}

// RequestTargetNode represents a request_target node.
type RequestTargetNode struct {
	TSNode        *ts.Node
	Interpolation []*InterpolationNode // field: interpolation
}

// SaveDirectiveNode represents a save_directive node.
type SaveDirectiveNode struct {
	TSNode *ts.Node
	Name   *IdentifierNode   // field: name
	Target *AssertTargetNode // field: target
}

// SepratorNode represents a seprator node.
type SepratorNode struct {
	TSNode *ts.Node
	Name   *RequestNameNode // field: name
}

// SourceFileNode represents a source_file node.
type SourceFileNode struct {
	TSNode   *ts.Node
	Block    []*RequestBlockNode // field: block
	Let      []*LetDirectiveNode // field: let
	Seprator []*SepratorNode     // field: seprator
}

// StringNode represents a string node.
type StringNode struct {
	TSNode *ts.Node
}

// UtilReferenceNode represents a util_reference node.
type UtilReferenceNode struct {
	TSNode   *ts.Node
	UtilName *IdentifierNode // field: util_name
}

// ValueReferenceNode represents a value_reference node.
type ValueReferenceNode struct {
	TSNode   *ts.Node
	Accessor []*AccessorNode // field: accessor
	Root     *IdentifierNode // field: root
}
