// Code generated by gen/main.go from node-types.json. DO NOT EDIT.

package ast

import ts "github.com/tree-sitter/go-tree-sitter"

type NodeKind string

const (
	AccessorKind            NodeKind = "accessor"
	ArgumentKind            NodeKind = "argument"
	ArgumentsKind           NodeKind = "arguments"
	AssertDirectiveKind     NodeKind = "assert_directive"
	AssertTargetKind        NodeKind = "assert_target"
	BodyTargetKind          NodeKind = "body_target"
	ComparatorOperatorKind  NodeKind = "comparator_operator"
	DigitKind               NodeKind = "digit"
	DirectiveLineKind       NodeKind = "directive_line"
	FieldLineKind           NodeKind = "field_line"
	FieldNameKind           NodeKind = "field_name"
	FieldPartKind           NodeKind = "field_part"
	FieldValueKind          NodeKind = "field_value"
	FieldValueSeperatorKind NodeKind = "field_value_seperator"
	FilePartKind            NodeKind = "file_part"
	HeaderTargetKind        NodeKind = "header_target"
	HttpVersionKind         NodeKind = "http_version"
	IdentifierKind          NodeKind = "identifier"
	IndexAccessKind         NodeKind = "index_access"
	InterpolationKind       NodeKind = "interpolation"
	InterpolationBodyKind   NodeKind = "interpolation_body"
	JsonLiteralKind         NodeKind = "json_literal"
	LetDirectiveKind        NodeKind = "let_directive"
	LetValueKind            NodeKind = "let_value"
	MemberAccessKind        NodeKind = "member_access"
	MessageBodyKind         NodeKind = "message_body"
	MethodKind              NodeKind = "method"
	MultipartBodyKind       NodeKind = "multipart_body"
	MultipartFieldKeyKind   NodeKind = "multipart_field_key"
	MultipartFileKeyKind    NodeKind = "multipart_file_key"
	MultipartPartKind       NodeKind = "multipart_part"
	NumberKind              NodeKind = "number"
	OctetBodyKind           NodeKind = "octet_body"
	QuotedPathKind          NodeKind = "quoted_path"
	RequestBlockKind        NodeKind = "request_block"
	RequestLineKind         NodeKind = "request_line"
	RequestNameKind         NodeKind = "request_name"
	RequestTargetKind       NodeKind = "request_target"
	SaveDirectiveKind       NodeKind = "save_directive"
	SepratorKind            NodeKind = "seprator"
	SourceFileKind          NodeKind = "source_file"
	StartParenthesisKind    NodeKind = "start_parenthesis"
	StringKind              NodeKind = "string"
	TargetTextKind          NodeKind = "target_text"
	UtilReferenceKind       NodeKind = "util_reference"
	ValueReferenceKind      NodeKind = "value_reference"
	ValueTextKind           NodeKind = "value_text"
)

// AccessorNode represents a accessor node.
type AccessorNode struct {
	*ts.Node
}

// ArgumentNode represents a argument node.
type ArgumentNode struct {
	*ts.Node
	Value *ts.Node // field: value
}

// ArgumentsNode represents a arguments node.
type ArgumentsNode struct {
	*ts.Node
	Argument []*ArgumentNode // field: argument
}

// AssertDirectiveNode represents a assert_directive node.
type AssertDirectiveNode struct {
	*ts.Node
	Comparator *ComparatorOperatorNode // field: comparator
	Expected   *LetValueNode           // field: expected
	Target     *AssertTargetNode       // field: target
}

// AssertTargetNode represents a assert_target node.
type AssertTargetNode struct {
	*ts.Node
	Target *ts.Node // field: target
}

// BodyTargetNode represents a body_target node.
type BodyTargetNode struct {
	*ts.Node
	Accessor []*AccessorNode // field: accessor
}

// ComparatorOperatorNode represents a comparator_operator node.
type ComparatorOperatorNode struct {
	*ts.Node
}

// DigitNode represents a digit node.
type DigitNode struct {
	*ts.Node
}

// DirectiveLineNode represents a directive_line node.
type DirectiveLineNode struct {
	*ts.Node
	Directive *ts.Node // field: directive
}

// FieldLineNode represents a field_line node.
type FieldLineNode struct {
	*ts.Node
	Name  *FieldNameNode  // field: name
	Value *FieldValueNode // field: value
}

// FieldNameNode represents a field_name node.
type FieldNameNode struct {
	*ts.Node
}

// FieldPartNode represents a field_part node.
type FieldPartNode struct {
	*ts.Node
	Name  *IdentifierNode // field: name
	Value *ts.Node        // field: value
}

// FieldValueNode represents a field_value node.
type FieldValueNode struct {
	*ts.Node
	Interpolation    []*InterpolationNode    // field: interpolation
	StartParanthesis []*StartParenthesisNode // field: start_paranthesis
	Text             []*ValueTextNode        // field: text
}

// FieldValueSeperatorNode represents a field_value_seperator node.
type FieldValueSeperatorNode struct {
	*ts.Node
}

// FilePartNode represents a file_part node.
type FilePartNode struct {
	*ts.Node
	ContentType *StringNode     // field: content_type
	Name        *IdentifierNode // field: name
	Path        *QuotedPathNode // field: path
}

// HeaderTargetNode represents a header_target node.
type HeaderTargetNode struct {
	*ts.Node
	Name *FieldNameNode // field: name
}

// HttpVersionNode represents a http_version node.
type HttpVersionNode struct {
	*ts.Node
	Major *DigitNode // field: major
	Minor *DigitNode // field: minor
}

// IdentifierNode represents a identifier node.
type IdentifierNode struct {
	*ts.Node
}

// IndexAccessNode represents a index_access node.
type IndexAccessNode struct {
	*ts.Node
	Index *ts.Node // field: index
}

// InterpolationNode represents a interpolation node.
type InterpolationNode struct {
	*ts.Node
	Body *InterpolationBodyNode // field: body
}

// InterpolationBodyNode represents a interpolation_body node.
type InterpolationBodyNode struct {
	*ts.Node
	Ref *ts.Node // field: ref
}

// JsonLiteralNode represents a json_literal node.
type JsonLiteralNode struct {
	*ts.Node
	Value *ts.Node // field: value
}

// LetDirectiveNode represents a let_directive node.
type LetDirectiveNode struct {
	*ts.Node
	Name   *IdentifierNode // field: name
	Target *LetValueNode   // field: target
}

// LetValueNode represents a let_value node.
type LetValueNode struct {
	*ts.Node
	Value *ts.Node // field: value
}

// MemberAccessNode represents a member_access node.
type MemberAccessNode struct {
	*ts.Node
	Name *IdentifierNode // field: name
}

// MessageBodyNode represents a message_body node.
type MessageBodyNode struct {
	*ts.Node
	Body *ts.Node // field: body
}

// MethodNode represents a method node.
type MethodNode struct {
	*ts.Node
}

// MultipartBodyNode represents a multipart_body node.
type MultipartBodyNode struct {
	*ts.Node
	Part []*MultipartPartNode // field: part
}

// MultipartFieldKeyNode represents a multipart_field_key node.
type MultipartFieldKeyNode struct {
	*ts.Node
}

// MultipartFileKeyNode represents a multipart_file_key node.
type MultipartFileKeyNode struct {
	*ts.Node
}

// MultipartPartNode represents a multipart_part node.
type MultipartPartNode struct {
	*ts.Node
}

// NumberNode represents a number node.
type NumberNode struct {
	*ts.Node
}

// OctetBodyNode represents a octet_body node.
type OctetBodyNode struct {
	*ts.Node
}

// QuotedPathNode represents a quoted_path node.
type QuotedPathNode struct {
	*ts.Node
}

// RequestBlockNode represents a request_block node.
type RequestBlockNode struct {
	*ts.Node
	Body        *MessageBodyNode     // field: body
	Directive   []*DirectiveLineNode // field: directive
	FieldLine   []*FieldLineNode     // field: field_line
	RequestLine *RequestLineNode     // field: request_line
}

// RequestLineNode represents a request_line node.
type RequestLineNode struct {
	*ts.Node
	Method  *MethodNode        // field: method
	Target  *RequestTargetNode // field: target
	Version *HttpVersionNode   // field: version
}

// RequestNameNode represents a request_name node.
type RequestNameNode struct {
	*ts.Node
}

// RequestTargetNode represents a request_target node.
type RequestTargetNode struct {
	*ts.Node
	Interpolation    []*InterpolationNode    // field: interpolation
	StartParenthesis []*StartParenthesisNode // field: start_parenthesis
	Text             []*TargetTextNode       // field: text
}

// SaveDirectiveNode represents a save_directive node.
type SaveDirectiveNode struct {
	*ts.Node
	Name   *IdentifierNode   // field: name
	Target *AssertTargetNode // field: target
}

// SepratorNode represents a seprator node.
type SepratorNode struct {
	*ts.Node
	Name *RequestNameNode // field: name
}

// SourceFileNode represents a source_file node.
type SourceFileNode struct {
	*ts.Node
	Block    []*RequestBlockNode // field: block
	Let      []*LetDirectiveNode // field: let
	Seprator []*SepratorNode     // field: seprator
}

// StartParenthesisNode represents a start_parenthesis node.
type StartParenthesisNode struct {
	*ts.Node
}

// StringNode represents a string node.
type StringNode struct {
	*ts.Node
}

// TargetTextNode represents a target_text node.
type TargetTextNode struct {
	*ts.Node
}

// UtilReferenceNode represents a util_reference node.
type UtilReferenceNode struct {
	*ts.Node
	UtilName *IdentifierNode // field: util_name
}

// ValueReferenceNode represents a value_reference node.
type ValueReferenceNode struct {
	*ts.Node
	Accessor []*AccessorNode // field: accessor
	Root     *IdentifierNode // field: root
}

// ValueTextNode represents a value_text node.
type ValueTextNode struct {
	*ts.Node
}

// NewAccessorNode builds a AccessorNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewAccessorNode(n *ts.Node) AccessorNode {
	v := AccessorNode{Node: n}
	return v
}

// NewArgumentNode builds a ArgumentNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewArgumentNode(n *ts.Node) ArgumentNode {
	v := ArgumentNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "value":
				v.Value = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewArgumentsNode builds a ArgumentsNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewArgumentsNode(n *ts.Node) ArgumentsNode {
	v := ArgumentsNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "argument":
				c := NewArgumentNode(child)
				v.Argument = append(v.Argument, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewAssertDirectiveNode builds a AssertDirectiveNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewAssertDirectiveNode(n *ts.Node) AssertDirectiveNode {
	v := AssertDirectiveNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "comparator":
				c := NewComparatorOperatorNode(child)
				v.Comparator = &c
			case "expected":
				c := NewLetValueNode(child)
				v.Expected = &c
			case "target":
				c := NewAssertTargetNode(child)
				v.Target = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewAssertTargetNode builds a AssertTargetNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewAssertTargetNode(n *ts.Node) AssertTargetNode {
	v := AssertTargetNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "target":
				v.Target = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewBodyTargetNode builds a BodyTargetNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewBodyTargetNode(n *ts.Node) BodyTargetNode {
	v := BodyTargetNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "accessor":
				c := NewAccessorNode(child)
				v.Accessor = append(v.Accessor, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewComparatorOperatorNode builds a ComparatorOperatorNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewComparatorOperatorNode(n *ts.Node) ComparatorOperatorNode {
	v := ComparatorOperatorNode{Node: n}
	return v
}

// NewDigitNode builds a DigitNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewDigitNode(n *ts.Node) DigitNode {
	v := DigitNode{Node: n}
	return v
}

// NewDirectiveLineNode builds a DirectiveLineNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewDirectiveLineNode(n *ts.Node) DirectiveLineNode {
	v := DirectiveLineNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "directive":
				v.Directive = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewFieldLineNode builds a FieldLineNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFieldLineNode(n *ts.Node) FieldLineNode {
	v := FieldLineNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewFieldNameNode(child)
				v.Name = &c
			case "value":
				c := NewFieldValueNode(child)
				v.Value = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewFieldNameNode builds a FieldNameNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFieldNameNode(n *ts.Node) FieldNameNode {
	v := FieldNameNode{Node: n}
	return v
}

// NewFieldPartNode builds a FieldPartNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFieldPartNode(n *ts.Node) FieldPartNode {
	v := FieldPartNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewIdentifierNode(child)
				v.Name = &c
			case "value":
				v.Value = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewFieldValueNode builds a FieldValueNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFieldValueNode(n *ts.Node) FieldValueNode {
	v := FieldValueNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "interpolation":
				c := NewInterpolationNode(child)
				v.Interpolation = append(v.Interpolation, &c)
			case "start_paranthesis":
				c := NewStartParenthesisNode(child)
				v.StartParanthesis = append(v.StartParanthesis, &c)
			case "text":
				c := NewValueTextNode(child)
				v.Text = append(v.Text, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewFieldValueSeperatorNode builds a FieldValueSeperatorNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFieldValueSeperatorNode(n *ts.Node) FieldValueSeperatorNode {
	v := FieldValueSeperatorNode{Node: n}
	return v
}

// NewFilePartNode builds a FilePartNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewFilePartNode(n *ts.Node) FilePartNode {
	v := FilePartNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "content_type":
				c := NewStringNode(child)
				v.ContentType = &c
			case "name":
				c := NewIdentifierNode(child)
				v.Name = &c
			case "path":
				c := NewQuotedPathNode(child)
				v.Path = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewHeaderTargetNode builds a HeaderTargetNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewHeaderTargetNode(n *ts.Node) HeaderTargetNode {
	v := HeaderTargetNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewFieldNameNode(child)
				v.Name = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewHttpVersionNode builds a HttpVersionNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewHttpVersionNode(n *ts.Node) HttpVersionNode {
	v := HttpVersionNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "major":
				c := NewDigitNode(child)
				v.Major = &c
			case "minor":
				c := NewDigitNode(child)
				v.Minor = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewIdentifierNode builds a IdentifierNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewIdentifierNode(n *ts.Node) IdentifierNode {
	v := IdentifierNode{Node: n}
	return v
}

// NewIndexAccessNode builds a IndexAccessNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewIndexAccessNode(n *ts.Node) IndexAccessNode {
	v := IndexAccessNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "index":
				v.Index = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewInterpolationNode builds a InterpolationNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewInterpolationNode(n *ts.Node) InterpolationNode {
	v := InterpolationNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "body":
				c := NewInterpolationBodyNode(child)
				v.Body = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewInterpolationBodyNode builds a InterpolationBodyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewInterpolationBodyNode(n *ts.Node) InterpolationBodyNode {
	v := InterpolationBodyNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "ref":
				v.Ref = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewJsonLiteralNode builds a JsonLiteralNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewJsonLiteralNode(n *ts.Node) JsonLiteralNode {
	v := JsonLiteralNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "value":
				v.Value = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewLetDirectiveNode builds a LetDirectiveNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewLetDirectiveNode(n *ts.Node) LetDirectiveNode {
	v := LetDirectiveNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewIdentifierNode(child)
				v.Name = &c
			case "target":
				c := NewLetValueNode(child)
				v.Target = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewLetValueNode builds a LetValueNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewLetValueNode(n *ts.Node) LetValueNode {
	v := LetValueNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "value":
				v.Value = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewMemberAccessNode builds a MemberAccessNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMemberAccessNode(n *ts.Node) MemberAccessNode {
	v := MemberAccessNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewIdentifierNode(child)
				v.Name = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewMessageBodyNode builds a MessageBodyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMessageBodyNode(n *ts.Node) MessageBodyNode {
	v := MessageBodyNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "body":
				v.Body = child
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewMethodNode builds a MethodNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMethodNode(n *ts.Node) MethodNode {
	v := MethodNode{Node: n}
	return v
}

// NewMultipartBodyNode builds a MultipartBodyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMultipartBodyNode(n *ts.Node) MultipartBodyNode {
	v := MultipartBodyNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "part":
				c := NewMultipartPartNode(child)
				v.Part = append(v.Part, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewMultipartFieldKeyNode builds a MultipartFieldKeyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMultipartFieldKeyNode(n *ts.Node) MultipartFieldKeyNode {
	v := MultipartFieldKeyNode{Node: n}
	return v
}

// NewMultipartFileKeyNode builds a MultipartFileKeyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMultipartFileKeyNode(n *ts.Node) MultipartFileKeyNode {
	v := MultipartFileKeyNode{Node: n}
	return v
}

// NewMultipartPartNode builds a MultipartPartNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewMultipartPartNode(n *ts.Node) MultipartPartNode {
	v := MultipartPartNode{Node: n}
	return v
}

// NewNumberNode builds a NumberNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewNumberNode(n *ts.Node) NumberNode {
	v := NumberNode{Node: n}
	return v
}

// NewOctetBodyNode builds a OctetBodyNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewOctetBodyNode(n *ts.Node) OctetBodyNode {
	v := OctetBodyNode{Node: n}
	return v
}

// NewQuotedPathNode builds a QuotedPathNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewQuotedPathNode(n *ts.Node) QuotedPathNode {
	v := QuotedPathNode{Node: n}
	return v
}

// NewRequestBlockNode builds a RequestBlockNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewRequestBlockNode(n *ts.Node) RequestBlockNode {
	v := RequestBlockNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "body":
				c := NewMessageBodyNode(child)
				v.Body = &c
			case "directive":
				c := NewDirectiveLineNode(child)
				v.Directive = append(v.Directive, &c)
			case "field_line":
				c := NewFieldLineNode(child)
				v.FieldLine = append(v.FieldLine, &c)
			case "request_line":
				c := NewRequestLineNode(child)
				v.RequestLine = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewRequestLineNode builds a RequestLineNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewRequestLineNode(n *ts.Node) RequestLineNode {
	v := RequestLineNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "method":
				c := NewMethodNode(child)
				v.Method = &c
			case "target":
				c := NewRequestTargetNode(child)
				v.Target = &c
			case "version":
				c := NewHttpVersionNode(child)
				v.Version = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewRequestNameNode builds a RequestNameNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewRequestNameNode(n *ts.Node) RequestNameNode {
	v := RequestNameNode{Node: n}
	return v
}

// NewRequestTargetNode builds a RequestTargetNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewRequestTargetNode(n *ts.Node) RequestTargetNode {
	v := RequestTargetNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "interpolation":
				c := NewInterpolationNode(child)
				v.Interpolation = append(v.Interpolation, &c)
			case "start_parenthesis":
				c := NewStartParenthesisNode(child)
				v.StartParenthesis = append(v.StartParenthesis, &c)
			case "text":
				c := NewTargetTextNode(child)
				v.Text = append(v.Text, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewSaveDirectiveNode builds a SaveDirectiveNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewSaveDirectiveNode(n *ts.Node) SaveDirectiveNode {
	v := SaveDirectiveNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewIdentifierNode(child)
				v.Name = &c
			case "target":
				c := NewAssertTargetNode(child)
				v.Target = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewSepratorNode builds a SepratorNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewSepratorNode(n *ts.Node) SepratorNode {
	v := SepratorNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "name":
				c := NewRequestNameNode(child)
				v.Name = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewSourceFileNode builds a SourceFileNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewSourceFileNode(n *ts.Node) SourceFileNode {
	v := SourceFileNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "block":
				c := NewRequestBlockNode(child)
				v.Block = append(v.Block, &c)
			case "let":
				c := NewLetDirectiveNode(child)
				v.Let = append(v.Let, &c)
			case "seprator":
				c := NewSepratorNode(child)
				v.Seprator = append(v.Seprator, &c)
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewStartParenthesisNode builds a StartParenthesisNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewStartParenthesisNode(n *ts.Node) StartParenthesisNode {
	v := StartParenthesisNode{Node: n}
	return v
}

// NewStringNode builds a StringNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewStringNode(n *ts.Node) StringNode {
	v := StringNode{Node: n}
	return v
}

// NewTargetTextNode builds a TargetTextNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewTargetTextNode(n *ts.Node) TargetTextNode {
	v := TargetTextNode{Node: n}
	return v
}

// NewUtilReferenceNode builds a UtilReferenceNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewUtilReferenceNode(n *ts.Node) UtilReferenceNode {
	v := UtilReferenceNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "util_name":
				c := NewIdentifierNode(child)
				v.UtilName = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewValueReferenceNode builds a ValueReferenceNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewValueReferenceNode(n *ts.Node) ValueReferenceNode {
	v := ValueReferenceNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "accessor":
				c := NewAccessorNode(child)
				v.Accessor = append(v.Accessor, &c)
			case "root":
				c := NewIdentifierNode(child)
				v.Root = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewValueTextNode builds a ValueTextNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field by name.
func NewValueTextNode(n *ts.Node) ValueTextNode {
	v := ValueTextNode{Node: n}
	return v
}
