// Code generated by gen/main.go from node-types.json. DO NOT EDIT.

package ast

import ts "github.com/tree-sitter/go-tree-sitter"

type NodeKind string

const (
	HttpVersionKind   NodeKind = "http_version"
	RequestKind       NodeKind = "request"
	RequestLineKind   NodeKind = "request_line"
	RequestTargetKind NodeKind = "request_target"
	RequestTypeKind   NodeKind = "request_type"
	SourceFileKind    NodeKind = "source_file"
)

// HttpVersionNode represents a http_version node.
type HttpVersionNode struct {
	*ts.Node
}

// RequestNode represents a request node.
type RequestNode struct {
	*ts.Node
	RequestLine *RequestLineNode // field: request_line
}

// RequestLineNode represents a request_line node.
type RequestLineNode struct {
	*ts.Node
	Target  *RequestTargetNode // field: target
	Type    *RequestTypeNode   // field: type
	Version *HttpVersionNode   // field: version
}

// RequestTargetNode represents a request_target node.
type RequestTargetNode struct {
	*ts.Node
}

// RequestTypeNode represents a request_type node.
type RequestTypeNode struct {
	*ts.Node
}

// SourceFileNode represents a source_file node.
type SourceFileNode struct {
	*ts.Node
	Children []*RequestNode
}

// NewHttpVersionNode builds a HttpVersionNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewHttpVersionNode(n *ts.Node) HttpVersionNode {
	v := HttpVersionNode{Node: n}
	return v
}

// NewRequestNode builds a RequestNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewRequestNode(n *ts.Node) RequestNode {
	v := RequestNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "request_line":
				c := NewRequestLineNode(child)
				v.RequestLine = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewRequestLineNode builds a RequestLineNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewRequestLineNode(n *ts.Node) RequestLineNode {
	v := RequestLineNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			case "target":
				c := NewRequestTargetNode(child)
				v.Target = &c
			case "type":
				c := NewRequestTypeNode(child)
				v.Type = &c
			case "version":
				c := NewHttpVersionNode(child)
				v.Version = &c
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}

// NewRequestTargetNode builds a RequestTargetNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewRequestTargetNode(n *ts.Node) RequestTargetNode {
	v := RequestTargetNode{Node: n}
	return v
}

// NewRequestTypeNode builds a RequestTypeNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewRequestTypeNode(n *ts.Node) RequestTypeNode {
	v := RequestTypeNode{Node: n}
	return v
}

// NewSourceFileNode builds a SourceFileNode by visiting n's direct children once,
// via a TreeCursor, and routing each into its matching field or Children.
func NewSourceFileNode(n *ts.Node) SourceFileNode {
	v := SourceFileNode{Node: n}
	cursor := n.Walk()
	defer cursor.Close()
	if cursor.GotoFirstChild() {
		for {
			child := cursor.Node()
			switch cursor.FieldName() {
			default:
				switch child.Kind() {
				case "request":
					c := NewRequestNode(child)
					v.Children = append(v.Children, &c)
				}
			}
			if !cursor.GotoNextSibling() {
				break
			}
		}
	}
	return v
}
